name: blade_open_left_door

task_name: blade_open_left_door

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [14]
      type: low_dimx
  action:
    shape: [14]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.blade_dataset.BLADEDataset
  zarr_path: /viscam/projects/kdm/open_cabinet_door_left-zero_action_real_img_null_action_obs_horizon_2.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
