name: unblock_cabinet_door

task_name: unblock_cabinet_door

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    point_cloud:
      shape: [4096, 6]
      type: point_cloud
    agent_pos:
      shape: [13]
      type: low_dimx
  action:
    shape: [13]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.blade_dataset.BLADEDataset
  zarr_path: /viscam/projects/kdm/unblock_cabinet_doors-dp3_point_cloud.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.05
  max_train_episodes: 90
